@startuml

class Member{
     e-mail: String
}

class BoardMember

class Event{
    date : Date
    description : String
    assign(l : Location) : void
}

class Conference{
    max_attendees : Integer
}

class BoardMeeting

class Location{
    description : String
    address : String
}

class Person{
    name : String
}

class AAUOC {
    newLocalitation(l : Location): void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}

AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Location


Event <|-- Conference
Event <|-- BoardMeeting
Event "0..*" -- "0..*" Member : attendsTo
Event "0..*" -- "1" Location : IsLocatedIn

Person <|-- Member
Member <|--BoardMember



Person "0..*" -- "0..*" Conference : attendsTo

BoardMember "0..*" -- "0..*" BoardMeeting : attendsTo

@enduml